import React from 'react'
import styles from '../NossaHistoria/NossaHistoria.module.scss';
const NossaHistoria = () => {
  return (
    <div className={styles.container}>
    <h1>Nossa Historia</h1>
    <p>O projeto iniciou-se em outubro de 2018 a partir de uma ideia dos irmãos (André e Andressa) moradores da comunidade da Chácara do Primeiro, no bairro Coronel Aparício Borges, localizado na cidade de Porto Alegre/RS. Os irmãos viram a necessidade dos sobrinhos e vizinhos (crianças e adolescentes) de possuir aulas de reforço escolar em horário inverso as aulas escolares, pois essas crianças e adolescentes possuíam muitas dúvidas e vontade de aprender, tendo em vista, que as escolas não conseguem suprir essas dúvidas e aprendizados dentro do período de um turno. Em conversa, os irmãos juntamente com alguns membros da família foram surgindo ideias, assim, o André, começou a dar as aulas de reforço escolar para faixa etária de 6 a 17 anos, a Andressa ajudava-o em algumas demandas e a fazer a chamada das crianças, o pai deles deu a ideia da criação de uma biblioteca comunitária e eles conseguiram doações de livros. Com o passar do tempo o número de alunos estava maior, e com várias dúvidas sobre as matérias que tinham mais dificuldades. Com isso, pela parte da noite (depois do horário da escola), juntaram-se para sanar essas dúvidas e estudarem juntos. O André acabou se mudando da comunidade, com isso, as aulas de reforço escolar passaram por algumas dificuldades. Para as crianças não ficarem na rua, depois do horário da escola, a Andressa deu continuidade com atividades que pudessem ajudar no aprendizado deles, de início tirava do próprio bolso o valor para as impressões de atividades, com o tempo começou a buscar voluntário, parceiros e doações para manter o projeto (dinheiro, brinquedos, material escolar, comida para festas comemorativas, etc.) Assim nomeando de CAD (Crescer, Aprender e se Divertir). Em 2020 André retorna para agregar nas atividades do projeto. Passamos também a atender crianças menores, que acabavam indo com os irmãos e primos que já participavam das atividades, então foi implementado no ano de 2020 um espaço Kids atendendo faixa etária de 2 a 5 anos, assim, os maiores poderiam dar 100% de atenção as atividades O projeto vai além, pois ajuda aos moradores e amigos da comunidade onde se insere. Aos poucos foram surgindo novos voluntários que atualmente ajudam nas arrecadações de doação e no planejamento das atividades do projeto. Atualmente o CAD atende crianças e adolescentes de 02 a 17 anos em situação de vulnerabilidade e risco social.</p>
    
    </div>
  )
}

export default NossaHistoria